# 변수명은 자유롭지만 알기 쉽게 지어주세요.
GOOGLE_CLIENT_ID: "진짜_구글_아이디"
GOOGLE_CLIENT_SECRET: "진짜_구글_비밀번호"

KAKAO_CLIENT_ID: "진짜_카카오_아이디"
KAKAO_CLIENT_SECRET: "진짜_카카오_비밀번호"

NAVER_CLIENT_ID: "진짜_네이버_아이디"
NAVER_CLIENT_SECRET: "진짜_네이버_비밀번호"
