plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':core')
    implementation 'org.springframework.boot:spring-boot-starter-websocket'
    implementation 'org.springframework.boot:spring-boot-starter-security'
}

tasks.named('bootRun') {
    dependsOn rootProject.tasks.named('setupGitHooks')
}