services:
    postgres:
        image: postgres:16
        container_name: local-postgres
        environment:
            POSTGRES_USER: calendar
            POSTGRES_PASSWORD: Asd!23QwE4%6
            POSTGRES_DB: hswy
        ports:
            - "5432:5432"
        volumes:
            - "../storage/postgres:/var/lib/postgresql/data"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U calendar -d hswy"]
            interval: 5s
            timeout: 5s
            retries: 10
    redis:
        image: redis:7
        container_name: local-redis
        ports:
            - "6379:6379"
        volumes:
            - "../storage/redis:/data"
        command: redis-server --appendonly yes
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 5s
            timeout: 5s
            retries: 10